apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysecret-deployment
  namespace: <your SN labs namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/cache/nginx/client_temp && chmod -R 777 /var/cache/nginx']
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        securityContext:
          runAsUser: 0
      containers:
      - name: myapp
        image: myapp:v1
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}
